(module utils (for)
  (import scheme)

  (define-syntax for
    (syntax-rules (to upto)
      ((_ n = s to e . forms)
       (let loop ((n s))
         (when (<= n e)
           (begin . forms)
           (loop (add1 n)))))
      ((_ n = e downto s . forms)
       (let loop ((n e))
         (when (>= n s)
           (begin . forms)
           (loop (sub1 n))))))))
